### ISSUE TITLE
NPI: Vaccines, Masking, school closures

### ISSUE THREAD

**Issue by gvegayon** [UofUEpiBio/epiworldRShiny#2]
This is based on the following user story:

As an **Epidemiologist**, I would like to **add tools such as (vaccines, masking, school closures, etc.)** so I can **measure changes in disease spread due to public health interventions.**

- [x] Working slider for % of Vaccines. 
- [x] Working slider for % of Masking.
- [x] Working slider for % of School closures.
- [x] Define the proper language for each.

**Comment by gvegayon** [comment]
Awesome, @derekmeyer37! I see you finished all this. Is the new version up?

**Comment by derekmeyer37** [comment]
> Awesome, @derekmeyer37! I see you finished all this. Is the new version up?

@gvegayon Yes! The new version is published.

**Comment by gvegayon** [comment]
Terrific, make sure you pull the repo before starting to work on it. I made some big changes!

**Comment by derekmeyer37** [comment]
I saw your changes, looks very cleaned up as always!
